[package]
name = "wfb-ng"
version = "0.0.0"
edition = "2021"
build = "build.rs"

[lib]
path = "rust/lib.rs"

[[bin]]
name = "wfb_rx"
path = "rust/bin/wfb_rx.rs"

[[bin]]
name = "wfb_tx"
path = "rust/bin/wfb_tx.rs"

[[bin]]
name = "wfb_keygen"
path = "rust/bin/wfb_keygen.rs"

[[bin]]
name = "wfb_tx_cmd"
path = "rust/bin/wfb_tx_cmd.rs"

[[bin]]
name = "wfb_tun"
path = "rust/bin/wfb_tun.rs"

[[bin]]
name = "wfb_rtsp"
path = "rust/bin/wfb_rtsp.rs"

[[bin]]
name = "fec_test"
path = "rust/bin/fec_test.rs"

[[bin]]
name = "libsodium_test"
path = "rust/bin/libsodium_test.rs"

[dependencies]
getopts = "0.2"
glib = "0.21"
gstreamer = "0.24"
gstreamer-rtsp-server = "0.24"
libc = "0.2"
libsodium-sys = "0.2"
memoffset = "0.9"
pcap-sys = "0.1"

